function fcn_saveSetup(handles)
% Saves the setup parameters

% Get parameters
Setup = {
    get(handles.edit_angVis,'String'),...
    get(handles.edit_wlVis,'String'),...
    get(handles.edit_angIR,'String'),...
    get(handles.edit_wlIR,'String'),...
    get(handles.edit_n1_sf,'String'),...
    get(handles.edit_n2_sf,'String'),...
    get(handles.edit_nBL_sf,'String'),...
    get(handles.edit_n1_vis,'String'),...
    get(handles.edit_n2_vis,'String'),...
    get(handles.edit_nBL_vis,'String'),...
    get(handles.edit_n1_ir,'String'),...
    get(handles.edit_n2_ir,'String'),...
    get(handles.edit_nBL_ir,'String'),...
    get(handles.edit_hypRatio,'String'),...
    get(handles.popup_moiety2,'Value'),...
    get(handles.edit_bondAngle,'String')
    }; %#ok<NASGU>

% Open save file dialog
[FileName,PathName] = uiputfile('*.mat', 'Save Setup');

% Return if no file was selected
if FileName == 0
    return
end

% Save the file
save([PathName FileName],'Setup');
% Update file name above table
set(handles.uipanel_setup,'Title',FileName);

%% Output
fprintf('Setup parameters saved as "%s".\n', FileName)

end